### ISSUE TITLE
How to run CMS?

### ISSUE THREAD

**Issue by sergey-pimenov** [jansmolders86/gh-cms#2]
Hi! Your project looks very interesting and solves my problems, this is exactly what I need.
But I can't understand how to run the CMS. Suppose I use https://github.com/jansmolders86/gh-cms-starter-template. What do I need to do to edit content using the GUI?

Very much waiting for your help, because I really need such a thing for several years. And it would be cool if this thing worked.

**Comment by jansmolders86** [comment]
So, you run this on a Github Page yourself or on a personal server. The CMS code itself is agnostic and dynamically generates itself based on the content presented. The link you mentioned is just a boilerplate for the "client", the CMS itself can be found here: https://github.com/jansmolders86/github-pages-cms

So it works like this:

1) You have a client, which is just a static website.  Coded they way you want and hosted as a github pages page. Create a full access token in the page's settings on Github.

2) You have a 2 JSON files.   

One for the CMS layout based on https://github.com/jdorn/json-editor  exampled here: https://github.com/jansmolders86/gh-cms-starter-template/blob/master/assets/json/schema.json

And one JSON matching the Schema with the actual content: 
https://github.com/jansmolders86/gh-cms-starter-template/blob/master/assets/json/content.json

4) convert the initial content.json to a base64 Blob and save that as a bin file. you can do that online using a tool like this (this is only the first time) https://www.base64encode.org/

5) Hook a a "middleware" in a way you're most comfortable. basically you just want to do an AJAX call, get the Blob, convert it back to a JSON and substitute or fill html with said content like in this example:
https://github.com/jansmolders86/gh-cms-starter-template/blob/master/assets/javascript/dev/locale.js

6) run the CMS on a Github pages of your choosing. Once it's up you'll get a login screen.

7) log in using the github email/token and provide the staic path to the blob and the proper branch. 
Once you log in, the CMS will use the Schema and the blob to generate the appropriate fields. 

Hope this helps!
